In [5]:
# Data load
import pandas as pd
df = pd.read_excel("sales_raw_500.xlsx")

In [6]:
df

     Order_ID Order_Date Customer Region  Product  Sales   Cost
0        1001 2023-01-13    Rohit  South   Mobile  23289  19118
1        1002 2023-10-07     Aman   West   Laptop   8905   5593
2        1003 2023-11-05    Rahul  South  Monitor  59987  39959
3        1004 2024-02-19    Rahul  South  Printer  49597  33892
4        1005 2024-01-26   Anjali  North   Laptop  54797  34468
..        ...        ...      ...    ...      ...    ...    ...
515      1389 2024-02-12    Vikas  North   Laptop  17924  12145
516      1496 2023-04-24    Kiran  North  Printer  23434  16388
517      1031 2023-02-19    Vikas   East  Printer  58883  43579
518      1317 2023-07-05     Aman  North   Laptop  76781  66865
519      1409 2024-01-16    Pooja  North  Monitor  19969  13586

[520 rows x 7 columns]

In [8]:
#EDA
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 520 entries, 0 to 519
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Order_ID    520 non-null    int64
 1   Order_Date  502 non-null    datetime64[ns]
 2   Customer    520 non-null    object
 3   Region      520 non-null    object
 4   Product     520 non-null    object
 5   Sales       520 non-null    int64
 6   Cost        520 non-null    int64
dtypes: datetime64[ns](1), int64(3), object(3)
memory usage: 28.6+ KB

          Order_ID                     Order_Date         Sales          Cost
count   520.000000                            502    520.000000    520.000000
mean   1250.867308  2023-08-18 09:36:34.422310656  41129.607692  30675.001923
min    1001.000000            2023-01-04 00:00:00   5205.000000   3272.000000
25%    1124.750000            2023-05-03 00:00:00  22015.750000  16388.000000
50%    1251.500000            2023-08-15 00:00:00  41044.000000  30349.000000
75%    1377.250000            2023-12-12 00:00:00  59245.000000  43363.500000
max    1500.000000            2024-03-26 00:00:00  79928.000000  71417.000000
std     145.030140                            NaN  21605.117122  16598.086873

In [12]:
#Checking for duplicate and removing them
df.duplicated()
df = df.drop_duplicates()
df

     Order_ID Order_Date Customer Region  Product  Sales   Cost
0        1001 2023-01-13    Rohit  South   Mobile  23289  19118
1        1002 2023-10-07     Aman   West   Laptop   8905   5593
2        1003 2023-11-05    Rahul  South  Monitor  59987  39959
3        1004 2024-02-19    Rahul  South  Printer  49597  33892
4        1005 2024-01-26   Anjali  North   Laptop  54797  34468
..        ...        ...      ...    ...      ...    ...    ...
495      1496 2023-04-24    Kiran  North  Printer  23434  16388
496      1497 2023-06-27   Anjali  South   Laptop  49007  35970
497      1498 2023-05-08     Aman   East   Tablet  19160  15636
498      1499        NaT    Pooja   West   Mobile  59266  44326
499      1500 2023-10-07    Vikas  North  Printer  34567  22426

[500 rows x 7 columns]

In [13]:
#fix date column
df['Order_Date'] = pd.to_datetime(df['Order_Date'] , errors = 'coerce')

In [14]:
df = df.dropna(subset = ['Order_Date'])

In [15]:
df

     Order_ID Order_Date Customer Region  Product  Sales   Cost
0        1001 2023-01-13    Rohit  South   Mobile  23289  19118
1        1002 2023-10-07     Aman   West   Laptop   8905   5593
2        1003 2023-11-05    Rahul  South  Monitor  59987  39959
3        1004 2024-02-19    Rahul  South  Printer  49597  33892
4        1005 2024-01-26   Anjali  North   Laptop  54797  34468
..        ...        ...      ...    ...      ...    ...    ...
494      1495 2023-10-18    Rahul  South  Monitor  46709  40931
495      1496 2023-04-24    Kiran  North  Printer  23434  16388
496      1497 2023-06-27   Anjali  South   Laptop  49007  35970
497      1498 2023-05-08     Aman   East   Tablet  19160  15636
499      1500 2023-10-07    Vikas  North  Printer  34567  22426

[482 rows x 7 columns]

In [16]:
df['Profit'] = df['Sales'] - df['Cost']
df['Year'] = df['Order_Date'].dt.year
df['Month'] = df['Order_Date'].dt.month

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_10756\3493934409.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Profit'] = df['Sales'] - df['Cost']
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_10756\3493934409.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Year'] = df['Order_Date'].dt.year
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_10756\3493934409.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Month'] = df['Order_Date'].dt.month

In [17]:
df

,Order_ID,Order_Date,Customer,Region,Product,Sales,Cost,Profit,Year,Month
0,1001,2023-01-13,Rohit,South,Mobile,23289,19118,4171,2023,1
1,1002,2023-10-07,Aman,West,Laptop,8905,5593,3312,2023,10
2,1003,2023-11-05,Rahul,South,Monitor,59987,39959,20028,2023,11
3,1004,2024-02-19,Rahul,South,Printer,49597,33892,15705,2024,2
4,1005,2024-01-26,Anjali,North,Laptop,54797,34468,20329,2024,1
...,...,...,...,...,...,...,...,...,...,...
494,1495,2023-10-18,Rahul,South,Monitor,46709,40931,5778,2023,10
495,1496,2023-04-24,Kiran,North,Printer,23434,16388,7046,2023,4
496,1497,2023-06-27,Anjali,South,Laptop,49007,35970,13037,2023,6
497,1498,2023-05-08,Aman,East,Tablet,19160,15636,3524,2023,5
499,1500,2023-10-07,Vikas,North,Printer,34567,22426,12141,2023,10

In [18]:
df.to_csv('Sales_cleaned.csv', index = False)

In [ ]:
# Data python + Excel +  Sql

In [19]:
from sqlalchemy import create_engine

In [20]:
pd.read_csv("Sales_cleaned.csv")

,Order_ID,Order_Date,Customer,Region,Product,Sales,Cost,Profit,Year,Month
0,1001,2023-01-13,Rohit,South,Mobile,23289,19118,4171,2023,1
1,1002,2023-10-07,Aman,West,Laptop,8905,5593,3312,2023,10
2,1003,2023-11-05,Rahul,South,Monitor,59987,39959,20028,2023,11
3,1004,2024-02-19,Rahul,South,Printer,49597,33892,15705,2024,2
4,1005,2024-01-26,Anjali,North,Laptop,54797,34468,20329,2024,1
...,...,...,...,...,...,...,...,...,...,...
477,1495,2023-10-18,Rahul,South,Monitor,46709,40931,5778,2023,10
478,1496,2023-04-24,Kiran,North,Printer,23434,16388,7046,2023,4
479,1497,2023-06-27,Anjali,South,Laptop,49007,35970,13037,2023,6
480,1498,2023-05-08,Aman,East,Tablet,19160,15636,3524,2023,5
481,1500,2023-10-07,Vikas,North,Printer,34567,22426,12141,2023,10

In [22]:
engine = create_engine('mysql+pymysql://root:password@localhost:3306/Salesdb')

In [23]:
df.to_sql(name = 'Sales_data' , con = engine, if_exists = 'replace', index = False)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_10756\1700552610.py:1: UserWarning: The provided table name 'Sales_data' is not found exactly as such in the database after writing the table, possibly due to case sensitivity issues. Consider using lower case table names.
  df.to_sql(name = 'Sales_data' , con = engine, if_exists = 'replace', index = False)

482